build:
  image: danieletorelli/sbt
  environment:
    - COURSIER_CACHE=/drone/cache/coursier
  commands:
    - export SBT_OPTS="-Xmx24G -XX:MaxPermSize=4G -Xss4M"
    - test -d /drone/.sbt && cp -a /drone/.sbt /root
    - rm -rf /drone/.sbt

    - test -d /drone/.ivy2 && cp -a /drone/.ivy2 /root
    - rm -rf /drone/.ivy2

    - sbt compile test

    - cp -a /root/.ivy2 /drone
    - cp -a /root/.sbt /drone
cache:
  mount:
    - /drone/.sbt
    - /drone/.ivy2
    - /drone/cache
