language: nix
dist: trusty
sudo: false
os:
  - linux
env:
  global:
    - TRAVIS_NODE_VERSION="8"

script:
  - bin/scalafmt --test
  - nix-shell -A scastie --command "sbt ci"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  yarn: true
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
